# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'macOS 10.13'

variables:
- group: React Native Variable Group

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.14.2'
  displayName: 'Install Node'

- script: npm install
  displayName: 'Install dependencies'

- script: gem install rails && rails -v
  displayName: 'gem install rails'

# - script: |
#     CALL gem install bundler
#     bundle install --retry=3 --jobs=4
#   displayName: 'bundle install'

- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'DistCertificates.p12'
    certPwd: $(P12password)
    keychain: 'temp'
    deleteCert: true
  displayName: Install Apple Certificate
  
- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'match_AdHoc_comnaicoawesomernapp.mobileprovision'
  displayName: 'Install Apple Provisioning Profile'

- script: |
    cd AwesomeRNApp/AwesomeRNApp/
    yarn
    bundle install
    bundle exec fastlane buildAndroid
    # fastlane buildIOS
  displayName: 'Build React native'