# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'macOS 10.13'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '9.7.1'
  displayName: 'Install Node'

- script: npm install
  displayName: 'Install dependencies'

# - task: InstallAppleCertificate@2
#   inputs:
#     certSecureFile: AppleDeveloperCertificate.p12
#     certPwd: $(P12password)
#     keychain: 'temp'
#     deleteCert: true
#   displayName: Install Apple Certificate
  
# - task: InstallAppleProvisioningProfile@1
#   inputs:
#     provisioningProfileLocation: 'secureFiles'
#     provProfileSecureFile: 'AppleProvisioningProfile.mobileprovision'
#   displayName: 'Install Apple Provisioning Profile'

- script: |
    cd AwesomeRNApp/AwesomeRNApp/
    bundle install
    fastlane buildAndroid
  displayName: 'Build android'