lane :buildAndroid do 
    begin
        
        gradle(task: 'clean', project_dir: 'android/')
        gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/',
            properties: {
            "android.injected.signing.store.file" => "android/keystores/AwesomeRNApp",
            "android.injected.signing.store.password" => "123456",
            "android.injected.signing.key.alias" => "key0",
            "android.injected.signing.key.password" => "123456",
            }
        )

        # upload_to_play_store(track: 'internal')

    rescue => ex
        UI.error ex
    end
end