lane :buildAndroid do 
    begin
        
        gradle(task: 'clean', project_dir: 'android/')
        gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/',
            properties: {
            "android.injected.signing.store.file" => "android/keystores/AwesomeRNApp",
            "android.injected.signing.store.password" => "123456",
            "android.injected.signing.key.alias" => "key0",
            "android.injected.signing.key.password" => "123456",
            }
        )

        # upload_to_play_store(track: 'internal')

        cocoapods(
            clean: true,
            podfile: './ios/Podfile'
        )

        gym

        upload_to_dropbox(
            file_path: "./iOSbuild/manifest.plist",
            dropbox_path: "/AwesomeRNApp",
            app_key: '30pj8qrn6fg0n9m',
            app_secret: '8vxko3iop0gdxhg',
            keychain_password: 'vinu123'
        )

    rescue => ex
        UI.error ex
    end
end