# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AwesomeRNApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AwesomeRNApp

  target 'AwesomeRNApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AwesomeRNAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
